"use client"

import { CacheProvider } from '@chakra-ui/next-js'
import { ChakraProvider } from '@chakra-ui/react'
import './globals.css'
import { Inter } from 'next/font/google'
import Navbar from './Component/Header'
import { Metadata } from 'next'
import { BlogProvider } from './context/BlogContext'
import { Footer } from './Component/Footer'


const inter = Inter({ subsets: ['latin'] })

export const metadata:Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning={true} >
      
      
        <body className="container px-4 xl:px-40 mx-auto ">
        {/* <CacheProvider> */}
        <ChakraProvider>
        <Navbar/>
        <BlogProvider>
          {children}
        </BlogProvider> 
        <Footer/>
          </ChakraProvider>
        {/* </CacheProvider>  */}
        </body>
    </html>
  )
}
